# Generated by Django 5.1 on 2025-01-29 14:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('clientid', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(8)])),
                ('dateofbirth', models.DateField(verbose_name='date of birth')),
                ('failed_attempts', models.IntegerField(default=0)),
                ('lockout_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='createroom',
            fields=[
                ('roomid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('roomdescription', models.TextField()),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('roomid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('roomdescription', models.TextField()),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.registration')),
            ],
        ),
    ]
