# Generated by Django 5.1 on 2024-12-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='clientid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
