# Generated by Django 5.1 on 2025-02-03 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_room_capacity_room_participants_delete_createroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='topics',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('updatetime', models.DateTimeField(auto_now=True)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.registration')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.room')),
            ],
        ),
    ]
