# Generated by Django 5.1 on 2024-12-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_registration_clientid'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registration',
            name='lockout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
