# Generated by Django 5.1 on 2025-01-26 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_registration_failed_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('roomid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('roomdescription', models.TextField()),
                ('updatetime', models.DateTimeField(auto_now=True, null=True)),
                ('createdtime', models.DateTimeField(auto_now_add=True)),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.registration')),
            ],
        ),
    ]
