# Generated by Django 5.1 on 2025-01-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
